### ISSUE TITLE
Pause Menü

### ISSUE THREAD

**Issue by Alexx882** [W3D3/ColorTrip#5]
Pausemenü während dem Spiel

**Comment by GustavAT** [comment]
DONE, see:  72b63d8c09db6209414cf1e060b9d7c130b43655

The following options/information is shown:
- **Resume**: resume the game
- **Checkpoint**: Respawn at the last checkpoint
- **Restart**: Restart this level
- **Main Menu**: Go to main menu
- Showing Stats: Current **Playtime** and **Deaths**
